# Generated by Django 5.0.7 on 2024-08-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_skill_competency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='competency',
            field=models.CharField(choices=[('novice', 'Novice'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('proficient', 'Proficient'), ('expert', 'Expert')], max_length=20),
        ),
    ]
