# Generated by Django 5.0.7 on 2024-08-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_skill_competency'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
