# Generated by Django 5.0.7 on 2024-08-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_project_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='search_keyword',
            field=models.CharField(blank=True, help_text='keyword to search for videos to learn', max_length=100),
        ),
    ]
