# Generated by Django 5.0.7 on 2024-08-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmenttemplate',
            old_name='training',
            new_name='trainings',
        ),
        migrations.AddField(
            model_name='assignment',
            name='total_time_watched',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='training',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
