# Generated by Django 5.0.7 on 2024-08-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
    ]
